version: "3.8"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '4000:8000'
  client:
    build: ./client
    container_name: client_c
    ports:
      - '5173:3000'
    stdin_open: true
    tty: true